"""Regla de autoría del grupo: scripts/comprobar_autoria.py y el hook commit-msg."""
from __future__ import annotations

import importlib.util
import io
import subprocess
import sys
from pathlib import Path

import pytest

RAIZ = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location('comprobar_autoria', RAIZ / 'scripts' / 'comprobar_autoria.py')
A = importlib.util.module_from_spec(_spec)
sys.modules['comprobar_autoria'] = A
_spec.loader.exec_module(A)

MENSAJE_MALO = (
    'Portal web: rediseño\n\nCuerpo del mensaje.\n\n'
    'Co-Authored-By: Asistente <noreply@ejemplo.com>\n'
)


@pytest.mark.parametrize('linea', [
    'Co-Authored-By: Alguien <noreply@ejemplo.com>',
    'co-authored-by: alguien <a@b.c>',
    '  Co-authored-by:Alguien',
    '\N{ROBOT FACE} Generated with [Herramienta](https://ejemplo.com)',
    'Generated by una herramienta',
])
def test_detecta_atribuciones(linea):
    assert A.lineas_prohibidas(f'Título\n\n{linea}\n') == [linea.strip()]


@pytest.mark.parametrize('texto', [
    'Integra el portal web',
    'Los co-autores del informe somos el grupo',
    'Se generan los agregados con Spark',
    'Authored-By en la tabla de la bitácora',
])
def test_no_marca_texto_normal(texto):
    assert A.lineas_prohibidas(texto) == []


def test_limpiar_quita_la_linea_y_el_hueco_final():
    assert A.limpiar(MENSAJE_MALO) == 'Portal web: rediseño\n\nCuerpo del mensaje.\n'


def test_modo_mensaje_limpia_o_rechaza(tmp_path):
    f = tmp_path / 'COMMIT_EDITMSG'
    f.write_text(MENSAJE_MALO, encoding='utf-8')
    assert A.main(['--mensaje', str(f)]) == 1
    assert A.main(['--mensaje', str(f), '--limpiar']) == 0
    assert 'Co-Authored-By' not in f.read_text(encoding='utf-8')
    assert A.main(['--mensaje', str(f)]) == 0


def test_modo_texto_para_el_pull_request(monkeypatch):
    monkeypatch.setattr(sys, 'stdin', io.StringIO('Título\n\n## Resumen\n- cambios\n'))
    assert A.main(['--texto']) == 0
    monkeypatch.setattr(sys, 'stdin', io.StringIO('Título\n\n\N{ROBOT FACE} Generated with [X](https://x)\n'))
    assert A.main(['--texto']) == 1


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(['git', '-C', str(repo), *args], check=True, capture_output=True, text=True).stdout


@pytest.fixture
def repo(tmp_path):
    _git(tmp_path, 'init', '-q', '-b', 'main')
    _git(tmp_path, 'config', 'user.name', 'Javier Saguar')
    _git(tmp_path, 'config', 'user.email', 'grupo@ejemplo.com')
    _git(tmp_path, 'config', 'commit.gpgsign', 'false')
    return tmp_path


def test_modo_rango_encuentra_el_commit(repo, monkeypatch):
    _git(repo, 'commit', '-q', '--allow-empty', '-m', 'Primero')
    base = _git(repo, 'rev-parse', 'HEAD').strip()
    _git(repo, 'commit', '-q', '--allow-empty', '-m', MENSAJE_MALO)
    monkeypatch.chdir(repo)
    assert A.main(['--rango', base]) == 0
    assert A.main(['--rango', f'{base}..HEAD']) == 1


def test_hook_commit_msg_limpia_el_commit(repo):
    hooks = repo / '.githooks'
    hooks.mkdir()
    (hooks / 'commit-msg').write_text(
        (RAIZ / '.githooks' / 'commit-msg').read_text(encoding='utf-8'), encoding='utf-8')
    (hooks / 'commit-msg').chmod(0o755)
    (repo / 'scripts').mkdir()
    (repo / 'scripts' / 'comprobar_autoria.py').write_text(
        (RAIZ / 'scripts' / 'comprobar_autoria.py').read_text(encoding='utf-8'), encoding='utf-8')
    _git(repo, 'config', 'core.hooksPath', '.githooks')
    _git(repo, 'commit', '-q', '--allow-empty', '-m', MENSAJE_MALO)
    mensaje = _git(repo, 'log', '-1', '--format=%B')
    assert 'Co-Authored-By' not in mensaje
    assert mensaje.startswith('Portal web: rediseño')
